version: '3.8'

services:

  backend:
    build: ./Livyfy
    ports:
      - "8080:8080"
    depends_on:
      - db
      - ai-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/housing_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: housing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/data
volumes:
  chroma_data: