server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/housing_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: livyfy-backend
